const userTypes = {
    LOGIN_USER   : 'LOGIN_USER',
    SIGN_UP_USER : 'SIGN_UP_USER',
    SIGN_OUT_USER: 'SIGN_OUT_USER',
    FETCH_USERS_START:'FETCH_USERS_START',
    FETCH_USERS_SUCCESS:'FETCH_USERS_SUCCESS',
    FETCH_USERS_ERROR:'FETCH_USERS_ERROR',
};

export default userTypes;